### ISSUE TITLE
Problem deploy onto the systemd service

### ISSUE THREAD

**Issue by pungoyal** [strongloop/strong-service-systemd#4]
I have a vanilla loopback app [https://github.com/pungoyal/node-app] which I am trying to deploy onto a systemd service running on a CentOS 7 EC2 instance.

I build the loopback app by `sl-build -n` 

```
[user@ip-172-31-49-77 node-app]$ sl-build -n
Running `npm install --ignore-scripts`
Running `npm prune --production`
Packing application in to ../node-app-1.0.0.tgz
[user@ip-172-31-49-77 node-app]$
```

Deploy using `sl-deploy` on the same host as the systemd service.

```
[ugc@ip-172-31-49-77 node-app]$ sl-deploy
Deployed `../node-app-1.0.0.tgz` as `node-app` to `http://127.0.0.1:8701/`
[ugc@ip-172-31-49-77 node-app]$
```

The error I get from `journalctl -f --no-tail` is:

```
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal node[2909]: events.js:141
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal node[2909]: throw er; // Unhandled 'error' event
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal node[2909]: ^
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal node[2909]: Error: spawn npm ENOENT
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal node[2909]: at exports._errnoException (util.js:870:11)
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal node[2909]: at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal node[2909]: at Process.onexit (/opt/node-v4.3.2-linux-x64/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal node[2909]: at onErrorNT (internal/child_process.js:344:16)
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal node[2909]: at /opt/node-v4.3.2-linux-x64/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal node[2909]: at nextTickCallbackWith2Args (node.js:437:9)
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal node[2909]: at process._tickDomainCallback (node.js:392:17)
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal node[2909]: at process.<anonymous> (/opt/node-v4.3.2-linux-x64/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal systemd[1]: strong-pm.service: main process exited, code=exited, status=1/FAILURE
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal systemd[1]: Unit strong-pm.service entered failed state.
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal systemd[1]: strong-pm.service failed.
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal systemd[1]: strong-pm.service holdoff time over, scheduling restart.
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal systemd[1]: Started StrongLoop Process Manager.
Apr 01 10:19:19 ip-172-31-49-77.ec2.internal systemd[1]: Starting StrongLoop Process Manager...
Apr 01 10:19:21 ip-172-31-49-77.ec2.internal node[2932]: sl-pm.js(2932): StrongLoop PM v5.2.0 (API v6.1.0) on port `8701`
Apr 01 10:19:21 ip-172-31-49-77.ec2.internal node[2932]: sl-pm.js(2932): Base folder `/var/lib/strong-pm`
Apr 01 10:19:21 ip-172-31-49-77.ec2.internal node[2932]: sl-pm.js(2932): Applications on port `3000 + service ID`
Apr 01 10:19:21 ip-172-31-49-77.ec2.internal node[2932]: Browse your REST API at http://127.0.0.1:8701/explorer
```

Now the weird thing is that if I stop the systemd service and `sl-deploy` to `slpm` running as non root user, the node app starts fine as:

```
npm WARN package.json node-app@1.0.0 No license field.
Run request for commit "default/npm-pack" on current (none)
Start Runner: commit default/npm-pack
2016-04-01T05:00:42.031Z pid:3171 worker:0 INFO strong-agent v2.0.2 profiling app 'node-app' pid '3171'
2016-04-01T05:00:42.038Z pid:3171 worker:0 INFO strong-agent[3171] started profiling agent
2016-04-01T05:00:42.041Z pid:3171 worker:0 INFO supervisor starting (pid 3171)
2016-04-01T05:00:42.043Z pid:3171 worker:0 INFO strong-agent strong-agent using strong-cluster-control v2.2.1
2016-04-01T05:00:42.046Z pid:3171 worker:0 INFO supervisor reporting metrics to `internal:`
2016-04-01T05:00:42.056Z pid:3171 worker:0 INFO strong-agent not profiling, agent metrics requires a valid license.
2016-04-01T05:00:42.056Z pid:3171 worker:0 Please contact sales@strongloop.com for assistance.
2016-04-01T05:00:42.060Z pid:3171 worker:0 INFO supervisor size set to 1
2016-04-01T05:00:42.149Z pid:3171 worker:0 INFO supervisor started worker 1 (pid 3176)
2016-04-01T05:00:42.149Z pid:3171 worker:0 INFO supervisor resized to 1
2016-04-01T05:00:42.443Z pid:3176 worker:1 INFO strong-agent v2.0.2 profiling app 'node-app' pid '3176'
2016-04-01T05:00:42.443Z pid:3176 worker:1 INFO strong-agent[3176] started profiling agent
2016-04-01T05:00:43.363Z pid:3176 worker:1 INFO strong-agent not profiling, agent metrics requires a valid license.
2016-04-01T05:00:43.364Z pid:3176 worker:1 Please contact sales@strongloop.com for assistance.
2016-04-01T05:00:43.379Z pid:3176 worker:1 Web server listening at: http://0.0.0.0:3001
2016-04-01T05:00:43.380Z pid:3176 worker:1 Browse your REST API at http://0.0.0.0:3001/explorer
slpm: Service "1" listening on 0.0.0.0:3001
```

Where is the systemd service messing up?

**Comment by pungoyal** [comment]
Also, when I go to `/var/lib/strong-pm/svc/1/work/<hash>/` and run `node .` the app starts fine.

**Comment by rmg** [comment]
The error in the logs is from strong-pm itself failing to start. What do you see if you just run `sl-pm` itself as a regular user with no arguments? It should start up and just sit there doing nothing until you kill it. Does it crash or give you any error messages?

**Comment by rmg** [comment]
@pungoyal good catch in your comment in strongloop/strong-deploy#50!

Re-reading the error message here that is very likely the same root cause. When trying to install the dependencies, strong-pm is unable to find the `npm` executable.

Likely you need to add this line to your `/etc/systemd/system/strong-pm.service` file:

```
Environment=PATH=/opt/node-v4.3.2-linux-x64/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

You'll likely want to base the actual value off of what `echo PATH=$PATH` shows in your shell.

**Comment by pungoyal** [comment]
@rmg  I forgot to mention that I had added `export PATH="/opt/node/bin:$PATH"` in `/etc/profile`.

```
[root@ip-172-31-49-77 ~]# echo $PATH
/opt/node/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
[root@ip-172-31-49-77 ~]#
```

```
[root@ip-172-31-49-77 ~]# ll /opt/
total 3
lrwxrwxrwx. 1 ugc      ugc        26 Apr  1 08:18 node -> /opt/node-v4.3.2-linux-x64
drwxrwxr-x. 7 ugc      ugc      4096 Apr  1 08:19 node-v4.3.2-linux-x64
[root@ip-172-31-49-77 ~]#
```

**Comment by rmg** [comment]
I don't think the environment from /etc/profile is inherited by systemd. Are you able to verify?

**Comment by pungoyal** [comment]
@rmg you were right. Adding the PATH to ENVIRONMENT fixed the issue for me. Thanks!
